### ISSUE TITLE
[Crash]: Crash on Start (was working before)

### ISSUE THREAD

**Issue by enzomtpYT** [Fuzss/magnumtorch#16]
### Mod Loader (Required)

Forge

### Minecraft Version (Required)

1.20.1

### Mod Version (Required)

v8.0.0

### Notes (Required)

I don't really know how to reproduce but here is the whole story :

I created a 440 mods modpack, everything was working fine.
I tried to add 4 mods : "Tick Statis, Better Fabric Console, Item Blacklist, No Portals"
I saw the server crashing with a simple puzzleslib error, i removed the mods and then a magnum torch error appeared

Everything is server-sided, the server don't really crash it just never pass the error (is stuck when the error happens and nothing more appears in logs)

### Crash Report (Required)

Was not generated (file missing)

### latest.log (Optional)

https://mclo.gs/a8LiSRT

**Comment by Fuzss** [comment]
This is your issue. Please report it to ServerCore. Magnum Torch is simple the first mod to load the faulty class.

`Caused by: org.spongepowered.asm.mixin.injection.throwables.InjectionError: Critical injection failure: Redirector servercore$updateCachedChunks(Lnet/minecraft/class_3898;)Ljava/lang/Iterable; in #servercore:servercore.common.mixins.json:optimizations.ticking.chunk.cache.ServerChunkCacheMixin from mod servercore failed injection check, (0/1) succeeded. Scanned 1 target(s). Using refmap servercore-common-refmap.json`

**Comment by enzomtpYT** [comment]
Fixed on https://github.com/Wesley1808/ServerCore/issues/82
Was a dupe of https://github.com/Wesley1808/ServerCore/issues/79
