### ISSUE TITLE
[Bug]: Zombie Ambush/Raids Spawn through Magnum Torches in Dark Areas

### ISSUE THREAD

**Issue by Lucipo** [Fuzss/magnumtorch#23]
### Mod Loader (Required)

Forge

### Minecraft Version(s) (Required)

1.20.1

### Mod Version(s) (Required)

v8.0.2

### Other Mods Involved (Required)

⸺

### Notes (Required)

Large groups of zombies that sporadically spawn (in vanilla I believe) will spawn in unlit areas even if the magnum torch is already affecting the area. No other hostiles spawn in those areas. The issue is rare but removes all security provided by the magnum torch for things like afking and villagers, defeating the purpose of the magnum torch entirely. 

Issue happening live:

https://medal.tv/games/minecraft/clips/20lYz82p3tAIGh/d1337uvdQ2e4?invite=cr-MSx4Y3gsMTA1ODAwNzcs

### latest.log (Required)

https://pastebin.com/zxk0rnp0

**Comment by Fuzss** [comment]
That's intentional, I didn't want the torch to break raids since they can only be started by a player on purpose, which would lead to confusion when then nothing happens just because there is a magnum torch somewhere in range.

What you are encountering is a zombie siege. Both raids and sieges use the same spawn type unfortunately. I'd recommend adding `minecraft:zombie` to the `mob_blacklist`, so zombies won't spawn no matter of their spawn type.

You can also add `EVENT` to `blocked_spawn_types` to block both raids and sieges completely.

**Comment by Lucipo** [comment]
Thank you so much, I apologize if my wording came across like the annoying arrogant type on bug reports... I'll apply the fix right away :3

**Comment by Fuzss** [comment]
No worries! I should probably include zombies by default since sieges are not triggered by players as opposed to raids.
